server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: url-service

  data:
    redis:
#      host: ${SPRING_DATA_REDIS_HOST:redis}
#      port: ${SPRING_DATA_REDIS_PORT:6379}
      host: localhost
      port: 6379

    mongodb:
#      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:secret@mongo:27017/urlshortener?authSource=admin}
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:secret@localhost:27017/urlshortener?authSource=admin}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers

logging:
  level:
    root: INFO
    com.example.urlshortener: DEBUG