server:
  port: ${SERVER_PORT:8081}

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
        spring.json.write.dates.as.timestamps: true

  application:
    name: url-service

  data:
    redis:
#      host: ${SPRING_DATA_REDIS_HOST:redis}
#      port: ${SPRING_DATA_REDIS_PORT:6379}
      host: localhost
      port: 6379

    mongodb:
#      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:secret@mongo:27017/urlshortener?authSource=admin}
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:secret@localhost:27017/urlshortener?authSource=admin}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers

logging:
  level:
    root: INFO
    com.example.urlshortener: DEBUG