server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/user}
#    username: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 30000
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

logging:
  level:
    ROOT: ERROR