server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:broker:29092}
    consumer:
      group-id: url-clicks-group        # уникальный group id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.urlshortener.dto,com.urlshortener.model

  application:
    name: stat-service

  datasource:
#    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/user}
#    username: ${SPRING_DATASOURCE_USERNAME:postgres}
#    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/user}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      initialization-fail-timeout: 30000
  sql:
    init:
      mode: always
      data-locations: optional:classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

logging:
  level:
    ROOT: ERROR