services:
#  user-service:
#    build:
#      context: ./user-service
#      dockerfile: Dockerfile
#    container_name: user-service
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/user
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#    depends_on:
#      PostgreSQL:
#        condition: service_healthy
#    networks:
#      - backend-network
#
#  url-short-service:
#    build:
#      context: ./url-short-service
#      dockerfile: Dockerfile
#    container_name: url-short-service
#    ports:
#      - "8081:8081"
#    environment:
#      - SPRING_DATA_MONGODB_URI:mongodb://admin:secret@mongo:27017/urlshortener?authSource=admin
#      - SPRING_DATA_REDIS_HOST:redis
#      - SPRING_DATA_REDIS_PORT:6379
#      - SERVER_PORT=8081
#    depends_on:
#      mongo:
#        condition: service_healthy
#      redis:
#        condition: service_started
#    networks:
#      - backend-network

  PostgreSQL:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d user" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - backend-network

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --username admin --password secret --eval 'db.adminCommand(\"ping\")' || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend-network

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend-network

  broker:
    image: confluentinc/cp-kafka:7.0.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - backend-network

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    container_name: kafdrop
    ports:
      - "9000:9000"
    depends_on:
      - broker
    environment:
      KAFKA_BROKERCONNECT: "broker:29092"
      JVM_OPTS: "-Xms32M -Xmx64M"
    networks:
      - backend-network

volumes:
  redis-data:
  mongo-data:

networks:
  backend-network:
    driver: bridge