spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true

logging:
  level:
    ROOT: ERROR

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 50
  instances:
    serviceCircuitBreaker:
      baseConfig: default