server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
    instances:
      serviceCircuitBreaker:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers

logging:
  level:
    ROOT: WARN
    io.github.resilience4j.circuitbreaker: DEBUG